"use client";

import { useState, useEffect, useCallback } from "react";
import { useAuth } from "@/lib/supabase/auth-context";
import Navigation from "@/components/Navigation";
import Link from "next/link";
import Image from "next/image";
import {
  CharacterAutoGenerationSettings,
  CharacterProfileType,
} from "@/lib/types";

// Profile type display names and icons
const PROFILE_TYPES: { value: CharacterProfileType; label: string; emoji: string }[] = [
  { value: "influencer", label: "Influencer", emoji: "📸" },
  { value: "gamer", label: "Gamer", emoji: "🎮" },
  { value: "yoga_instructor", label: "Yoga Instructor", emoji: "🧘" },
  { value: "tech", label: "Tech", emoji: "💻" },
  { value: "billionaire", label: "Billionaire", emoji: "💰" },
  { value: "philosopher", label: "Philosopher", emoji: "📚" },
  { value: "fitness", label: "Fitness", emoji: "💪" },
  { value: "artist", label: "Artist", emoji: "🎨" },
  { value: "musician", label: "Musician", emoji: "🎵" },
  { value: "chef", label: "Chef", emoji: "👨‍🍳" },
  { value: "entrepreneur", label: "Entrepreneur", emoji: "🚀" },
  { value: "model", label: "Model", emoji: "👗" },
  { value: "scientist", label: "Scientist", emoji: "🔬" },
  { value: "traveler", label: "Traveler", emoji: "✈️" },
  { value: "wellness", label: "Wellness", emoji: "🌿" },
];

// Raw database response types (snake_case)
interface AutoGeneratedCharacterDB {
  id: string;
  user_id: string;
  settings_id: string;
  character_id: string;
  profile_type: string;
  generated_at: string;
  images_generated: number;
  is_complete: boolean;
  is_approved: boolean;
  is_released: boolean;
  characters: {
    id: string;
    name: string;
    description: string;
    thumbnail: string;
    category: string;
    is_public: boolean;
    personality: any;
    physical_attributes: any;
    tags: string[];
  };
}

interface QueueItemDB {
  id: string;
  user_id: string;
  settings_id: string;
  profile_type: string;
  gender: string;
  status: string;
  character_id: string | null;
  images_generated: number;
  total_images: number;
  error_message: string | null;
  created_at: string;
  started_at: string | null;
  completed_at: string | null;
}

interface SettingsData {
  exists: boolean;
  settings?: CharacterAutoGenerationSettings;
  defaults?: Partial<CharacterAutoGenerationSettings>;
  queue?: QueueItemDB[];
  recentCharacters?: AutoGeneratedCharacterDB[];
}

export default function CharacterAutomationPage() {
  const { user, isLoading: authLoading } = useAuth();
  const [settingsData, setSettingsData] = useState<SettingsData | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  
  // Form state
  const [isActive, setIsActive] = useState(false);
  const [charactersPerDay, setCharactersPerDay] = useState(5);
  const [imagesPerCharacter, setImagesPerCharacter] = useState(5);
  const [selectedProfileTypes, setSelectedProfileTypes] = useState<CharacterProfileType[]>([]);
  const [genderDistribution, setGenderDistribution] = useState({ male: 40, female: 50, nonBinary: 10 });
  const [makePublicByDefault, setMakePublicByDefault] = useState(false);
  
  // Tab state
  const [activeTab, setActiveTab] = useState<"settings" | "queue" | "characters">("settings");

  const fetchSettings = useCallback(async () => {
    try {
      const response = await fetch("/api/character-automation?includeStats=true");
      if (!response.ok) throw new Error("Failed to fetch settings");
      const data: SettingsData = await response.json();
      setSettingsData(data);
      
      // Initialize form with existing settings or defaults
      const s = data.settings || data.defaults;
      if (s) {
        setIsActive(s.isActive ?? false);
        setCharactersPerDay(s.charactersPerDay ?? 5);
        setImagesPerCharacter(s.imagesPerCharacter ?? 5);
        setSelectedProfileTypes(s.profileTypes ?? PROFILE_TYPES.slice(0, 6).map(p => p.value));
        setGenderDistribution(s.genderDistribution ?? { male: 40, female: 50, nonBinary: 10 });
        setMakePublicByDefault(s.makePublicByDefault ?? false);
      }
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (!authLoading && user) {
      fetchSettings();
    }
  }, [authLoading, user, fetchSettings]);

  // Auto-refresh queue when generating
  useEffect(() => {
    if (generating || (settingsData?.queue && settingsData.queue.length > 0)) {
      const interval = setInterval(fetchSettings, 5000);
      return () => clearInterval(interval);
    }
  }, [generating, settingsData?.queue, fetchSettings]);

  const handleSaveSettings = async () => {
    setSaving(true);
    setError(null);
    setSuccess(null);
    
    try {
      const response = await fetch("/api/character-automation", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          isActive,
          charactersPerDay,
          imagesPerCharacter,
          profileTypes: selectedProfileTypes,
          genderDistribution,
          makePublicByDefault,
        }),
      });
      
      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || "Failed to save settings");
      }
      
      const data = await response.json();
      setSettingsData(prev => prev ? { ...prev, exists: true, settings: data.settings } : null);
      setSuccess("Settings saved successfully!");
    } catch (err: any) {
      setError(err.message);
    } finally {
      setSaving(false);
    }
  };

  const handleToggleActive = async () => {
    setSaving(true);
    setError(null);
    
    try {
      const response = await fetch("/api/character-automation", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action: "toggle" }),
      });
      
      if (!response.ok) throw new Error("Failed to toggle");
      
      const data = await response.json();
      setIsActive(data.settings.isActive);
      setSettingsData(prev => prev ? { ...prev, settings: data.settings } : null);
      setSuccess(data.settings.isActive ? "Auto-generation started!" : "Auto-generation paused");
    } catch (err: any) {
      setError(err.message);
    } finally {
      setSaving(false);
    }
  };

  const handleManualGenerate = async () => {
    if (selectedProfileTypes.length === 0) {
      setError("Please select at least one profile type");
      return;
    }
    
    setGenerating(true);
    setError(null);
    setSuccess(null);
    
    try {
      // Pick random profile and gender
      const profileType = selectedProfileTypes[Math.floor(Math.random() * selectedProfileTypes.length)];
      const rand = Math.random() * 100;
      const gender = rand < genderDistribution.male ? "male" : rand < genderDistribution.male + genderDistribution.female ? "female" : "non-binary";
      
      const response = await fetch("/api/character-automation/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          profileType,
          gender,
          imagesPerCharacter,
          settingsId: settingsData?.settings?.id,
        }),
      });
      
      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || "Failed to generate character");
      }
      
      const data = await response.json();
      setSuccess(`Successfully generated ${data.character.name}!`);
      fetchSettings(); // Refresh to show new character
    } catch (err: any) {
      setError(err.message);
    } finally {
      setGenerating(false);
    }
  };

  const handleReleaseCharacter = async (characterId: string, isPublic: boolean) => {
    try {
      const response = await fetch("/api/character-automation/release", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ characterId, isPublic }),
      });
      
      if (!response.ok) throw new Error("Failed to update");
      fetchSettings();
    } catch (err: any) {
      setError(err.message);
    }
  };

  const toggleProfileType = (type: CharacterProfileType) => {
    setSelectedProfileTypes(prev => 
      prev.includes(type)
        ? prev.filter(t => t !== type)
        : [...prev, type]
    );
  };

  const handleGenderChange = (gender: "male" | "female" | "nonBinary", value: number) => {
    const newDist = { ...genderDistribution, [gender]: value };
    // Ensure total is 100
    const total = newDist.male + newDist.female + newDist.nonBinary;
    if (total !== 100) {
      // Adjust the others proportionally
      const diff = 100 - total;
      const others = gender === "male" ? ["female", "nonBinary"] : gender === "female" ? ["male", "nonBinary"] : ["male", "female"];
      const otherTotal = newDist[others[0] as keyof typeof newDist] + newDist[others[1] as keyof typeof newDist];
      if (otherTotal > 0) {
        newDist[others[0] as keyof typeof newDist] += Math.round(diff * (newDist[others[0] as keyof typeof newDist] / otherTotal));
        newDist[others[1] as keyof typeof newDist] = 100 - newDist[gender] - newDist[others[0] as keyof typeof newDist];
      }
    }
    setGenderDistribution(newDist);
  };

  if (authLoading) {
    return (
      <div className="min-h-screen bg-surface-dark flex items-center justify-center">
        <div className="animate-spin w-8 h-8 border-2 border-primary border-t-transparent rounded-full" />
      </div>
    );
  }

  if (!user) {
    return (
      <div className="min-h-screen bg-surface-dark text-white">
        <Navigation title="Character Automation" />
        <main className="max-w-7xl mx-auto px-4 py-8 pb-24 md:pb-8">
          <div className="text-center py-12">
            <h1 className="text-2xl font-bold mb-4">Sign in Required</h1>
            <p className="text-gray-400">Please sign in to access character automation.</p>
          </div>
        </main>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-surface-dark text-white">
      <Navigation title="Character Automation" />

      <main className="max-w-7xl mx-auto px-4 py-6 pb-24 md:pb-8">
        {/* Header */}
        <div className="mb-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <h1 className="text-2xl sm:text-3xl font-bold mb-1">🤖 Auto Character Generator</h1>
              <p className="text-gray-400 text-sm sm:text-base">
                Automatically generate diverse AI characters with unique profiles
              </p>
            </div>
            <Link
              href="/dashboard"
              className="text-primary hover:text-primary-light transition-colors text-sm"
            >
              ← Back to Dashboard
            </Link>
          </div>
        </div>

        {/* Alerts */}
        {error && (
          <div className="mb-4 p-4 bg-red-500/20 border border-red-500/50 rounded-xl text-red-300">
            {error}
            <button onClick={() => setError(null)} className="float-right text-red-300 hover:text-red-200">✕</button>
          </div>
        )}
        {success && (
          <div className="mb-4 p-4 bg-green-500/20 border border-green-500/50 rounded-xl text-green-300">
            {success}
            <button onClick={() => setSuccess(null)} className="float-right text-green-300 hover:text-green-200">✕</button>
          </div>
        )}

        {/* Stats Cards */}
        {settingsData?.settings && (
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-6">
            <div className="p-4 glass border border-border rounded-xl">
              <div className="text-2xl mb-1">{settingsData.settings.totalCharactersGenerated}</div>
              <div className="text-gray-400 text-sm">Total Characters</div>
            </div>
            <div className="p-4 glass border border-border rounded-xl">
              <div className="text-2xl mb-1">{settingsData.settings.totalImagesGenerated}</div>
              <div className="text-gray-400 text-sm">Total Images</div>
            </div>
            <div className="p-4 glass border border-border rounded-xl">
              <div className="text-2xl mb-1">{settingsData.queue?.length || 0}</div>
              <div className="text-gray-400 text-sm">In Queue</div>
            </div>
            <div className="p-4 glass border border-border rounded-xl">
              <div className={`text-2xl mb-1 ${settingsData.settings.isActive ? "text-green-400" : "text-gray-400"}`}>
                {settingsData.settings.isActive ? "●" : "○"}
              </div>
              <div className="text-gray-400 text-sm">{settingsData.settings.isActive ? "Active" : "Paused"}</div>
            </div>
          </div>
        )}

        {/* Tab Navigation */}
        <div className="flex gap-2 mb-6 overflow-x-auto pb-2">
          {[
            { id: "settings", label: "⚙️ Settings" },
            { id: "queue", label: `📋 Queue (${settingsData?.queue?.length || 0})` },
            { id: "characters", label: `👥 Characters (${settingsData?.recentCharacters?.length || 0})` },
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`px-4 py-2 rounded-lg whitespace-nowrap transition-all ${
                activeTab === tab.id
                  ? "gradient-primary font-semibold"
                  : "bg-surface-light text-gray-300 hover:bg-surface-light/80"
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {loading ? (
          <div className="flex items-center justify-center py-12">
            <div className="animate-spin w-8 h-8 border-2 border-primary border-t-transparent rounded-full" />
          </div>
        ) : (
          <>
            {/* Settings Tab */}
            {activeTab === "settings" && (
              <div className="space-y-6">
                {/* Quick Actions */}
                <div className="flex flex-col sm:flex-row gap-4">
                  <button
                    onClick={handleToggleActive}
                    disabled={saving || !settingsData?.exists}
                    className={`flex-1 px-6 py-4 rounded-xl font-semibold text-lg transition-all ${
                      isActive
                        ? "bg-red-500/20 border border-red-500/50 text-red-300 hover:bg-red-500/30"
                        : "gradient-primary hover:opacity-90"
                    } disabled:opacity-50`}
                  >
                    {saving ? "..." : isActive ? "⏸️ Pause Auto-Generation" : "▶️ Start Auto-Generation"}
                  </button>
                  <button
                    onClick={handleManualGenerate}
                    disabled={generating || selectedProfileTypes.length === 0}
                    className="flex-1 px-6 py-4 bg-surface-light border border-border rounded-xl font-semibold text-lg hover:border-primary/50 transition-all disabled:opacity-50"
                  >
                    {generating ? (
                      <span className="flex items-center justify-center gap-2">
                        <div className="animate-spin w-5 h-5 border-2 border-primary border-t-transparent rounded-full" />
                        Generating...
                      </span>
                    ) : (
                      "✨ Generate One Now"
                    )}
                  </button>
                </div>

                {/* Characters Per Day */}
                <div className="glass border border-border rounded-xl p-6">
                  <h3 className="font-semibold text-lg mb-4">📊 Generation Settings</h3>
                  
                  <div className="space-y-6">
                    <div>
                      <label className="block text-sm text-gray-400 mb-2">
                        Characters per day: <span className="text-white font-bold">{charactersPerDay}</span>
                      </label>
                      <input
                        type="range"
                        min="1"
                        max="20"
                        value={charactersPerDay}
                        onChange={(e) => setCharactersPerDay(parseInt(e.target.value))}
                        className="w-full h-2 bg-surface-light rounded-lg appearance-none cursor-pointer accent-primary"
                      />
                      <div className="flex justify-between text-xs text-gray-500 mt-1">
                        <span>1</span>
                        <span>20</span>
                      </div>
                    </div>

                    <div>
                      <label className="block text-sm text-gray-400 mb-2">
                        Images per character: <span className="text-white font-bold">{imagesPerCharacter}</span>
                      </label>
                      <input
                        type="range"
                        min="1"
                        max="10"
                        value={imagesPerCharacter}
                        onChange={(e) => setImagesPerCharacter(parseInt(e.target.value))}
                        className="w-full h-2 bg-surface-light rounded-lg appearance-none cursor-pointer accent-primary"
                      />
                      <div className="flex justify-between text-xs text-gray-500 mt-1">
                        <span>1</span>
                        <span>10</span>
                      </div>
                    </div>

                    <div className="flex items-center gap-3">
                      <button
                        onClick={() => setMakePublicByDefault(!makePublicByDefault)}
                        className={`relative w-12 h-6 rounded-full transition-colors ${
                          makePublicByDefault ? "bg-primary" : "bg-surface-light"
                        }`}
                      >
                        <span
                          className={`absolute top-1 left-1 w-4 h-4 bg-white rounded-full transition-transform ${
                            makePublicByDefault ? "translate-x-6" : ""
                          }`}
                        />
                      </button>
                      <span className="text-sm">Release characters as public by default</span>
                    </div>
                  </div>
                </div>

                {/* Profile Types */}
                <div className="glass border border-border rounded-xl p-6">
                  <h3 className="font-semibold text-lg mb-4">👤 Profile Types</h3>
                  <p className="text-sm text-gray-400 mb-4">Select the types of characters to generate</p>
                  
                  <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-2">
                    {PROFILE_TYPES.map(type => (
                      <button
                        key={type.value}
                        onClick={() => toggleProfileType(type.value)}
                        className={`p-3 rounded-xl text-sm font-medium transition-all ${
                          selectedProfileTypes.includes(type.value)
                            ? "gradient-primary"
                            : "bg-surface-light text-gray-300 hover:bg-surface-light/80"
                        }`}
                      >
                        <span className="text-lg mr-1">{type.emoji}</span>
                        <span className="hidden sm:inline">{type.label}</span>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Gender Distribution */}
                <div className="glass border border-border rounded-xl p-6">
                  <h3 className="font-semibold text-lg mb-4">⚖️ Gender Distribution</h3>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="flex items-center justify-between text-sm mb-2">
                        <span>👨 Male</span>
                        <span className="text-primary font-bold">{genderDistribution.male}%</span>
                      </label>
                      <input
                        type="range"
                        min="0"
                        max="100"
                        value={genderDistribution.male}
                        onChange={(e) => handleGenderChange("male", parseInt(e.target.value))}
                        className="w-full h-2 bg-blue-500/30 rounded-lg appearance-none cursor-pointer accent-blue-500"
                      />
                    </div>
                    <div>
                      <label className="flex items-center justify-between text-sm mb-2">
                        <span>👩 Female</span>
                        <span className="text-pink-400 font-bold">{genderDistribution.female}%</span>
                      </label>
                      <input
                        type="range"
                        min="0"
                        max="100"
                        value={genderDistribution.female}
                        onChange={(e) => handleGenderChange("female", parseInt(e.target.value))}
                        className="w-full h-2 bg-pink-500/30 rounded-lg appearance-none cursor-pointer accent-pink-500"
                      />
                    </div>
                    <div>
                      <label className="flex items-center justify-between text-sm mb-2">
                        <span>🧑 Non-binary</span>
                        <span className="text-purple-400 font-bold">{genderDistribution.nonBinary}%</span>
                      </label>
                      <input
                        type="range"
                        min="0"
                        max="100"
                        value={genderDistribution.nonBinary}
                        onChange={(e) => handleGenderChange("nonBinary", parseInt(e.target.value))}
                        className="w-full h-2 bg-purple-500/30 rounded-lg appearance-none cursor-pointer accent-purple-500"
                      />
                    </div>
                  </div>
                </div>

                {/* Save Button */}
                <button
                  onClick={handleSaveSettings}
                  disabled={saving}
                  className="w-full py-4 gradient-primary rounded-xl font-semibold text-lg hover:opacity-90 transition-all disabled:opacity-50"
                >
                  {saving ? "Saving..." : "💾 Save Settings"}
                </button>
              </div>
            )}

            {/* Queue Tab */}
            {activeTab === "queue" && (
              <div className="space-y-4">
                {!settingsData?.queue || settingsData.queue.length === 0 ? (
                  <div className="text-center py-12 glass border border-border rounded-xl">
                    <div className="text-4xl mb-4">📭</div>
                    <h3 className="text-xl font-semibold mb-2">No characters in queue</h3>
                    <p className="text-gray-400 mb-4">Start auto-generation or generate one manually</p>
                    <button
                      onClick={handleManualGenerate}
                      disabled={generating}
                      className="px-6 py-3 gradient-primary rounded-lg font-semibold hover:opacity-90 transition-all disabled:opacity-50"
                    >
                      {generating ? "Generating..." : "Generate Character"}
                    </button>
                  </div>
                ) : (
                  settingsData.queue.map((item, index) => (
                    <div key={item.id} className="glass border border-border rounded-xl p-4">
                      <div className="flex items-center gap-4">
                        <div className={`w-12 h-12 rounded-xl flex items-center justify-center ${
                          item.status === "generating" ? "animate-pulse bg-primary/30" : "bg-surface-light"
                        }`}>
                          {item.status === "generating" ? (
                            <div className="animate-spin w-6 h-6 border-2 border-primary border-t-transparent rounded-full" />
                          ) : (
                            <span className="text-xl">
                              {PROFILE_TYPES.find(t => t.value === item.profile_type)?.emoji || "👤"}
                            </span>
                          )}
                        </div>
                        <div className="flex-1">
                          <div className="font-semibold capitalize">
                            {item.profile_type.replace("_", " ")} ({item.gender})
                          </div>
                          <div className="text-sm text-gray-400">
                            {item.status === "generating"
                              ? `Generating image ${item.images_generated + 1} of ${item.total_images}...`
                              : item.status === "pending"
                              ? `Queued #${index + 1}`
                              : item.status}
                          </div>
                        </div>
                        {item.status === "generating" && (
                          <div className="w-20">
                            <div className="h-2 bg-surface-light rounded-full overflow-hidden">
                              <div
                                className="h-full bg-primary transition-all"
                                style={{ width: `${(item.images_generated / item.total_images) * 100}%` }}
                              />
                            </div>
                            <div className="text-xs text-center text-gray-400 mt-1">
                              {Math.round((item.images_generated / item.total_images) * 100)}%
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  ))
                )}
              </div>
            )}

            {/* Characters Tab */}
            {activeTab === "characters" && (
              <div className="space-y-4">
                {!settingsData?.recentCharacters || settingsData.recentCharacters.length === 0 ? (
                  <div className="text-center py-12 glass border border-border rounded-xl">
                    <div className="text-4xl mb-4">🎭</div>
                    <h3 className="text-xl font-semibold mb-2">No characters yet</h3>
                    <p className="text-gray-400 mb-4">Generate your first character to see them here</p>
                    <button
                      onClick={handleManualGenerate}
                      disabled={generating}
                      className="px-6 py-3 gradient-primary rounded-lg font-semibold hover:opacity-90 transition-all disabled:opacity-50"
                    >
                      {generating ? "Generating..." : "Generate Character"}
                    </button>
                  </div>
                ) : (
                  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                    {settingsData.recentCharacters.map((item) => {
                      const char = item.characters;
                      if (!char) return null;
                      
                      return (
                        <div key={item.id} className="glass border border-border rounded-xl overflow-hidden group">
                          <div className="aspect-square relative bg-surface-light">
                            {char.thumbnail ? (
                              <Image
                                src={char.thumbnail}
                                alt={char.name}
                                fill
                                className="object-cover"
                              />
                            ) : (
                              <div className="w-full h-full flex items-center justify-center">
                                <span className="text-6xl">
                                  {PROFILE_TYPES.find(t => t.value === item.profile_type)?.emoji || "👤"}
                                </span>
                              </div>
                            )}
                            <div className="absolute top-2 right-2">
                              <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                                char.is_public
                                  ? "bg-green-500/80 text-white"
                                  : "bg-gray-500/80 text-white"
                              }`}>
                                {char.is_public ? "Public" : "Private"}
                              </span>
                            </div>
                          </div>
                          <div className="p-4">
                            <div className="flex items-start justify-between mb-2">
                              <div>
                                <h3 className="font-semibold">{char.name}</h3>
                                <p className="text-sm text-primary-light capitalize">
                                  {item.profile_type.replace("_", " ")}
                                </p>
                              </div>
                              <span className="text-xs text-gray-400">
                                {item.images_generated} images
                              </span>
                            </div>
                            <p className="text-sm text-gray-400 line-clamp-2 mb-3">
                              {char.description}
                            </p>
                            <div className="flex gap-2">
                              <Link
                                href={`/dashboard/character/${char.id}`}
                                className="flex-1 text-center py-2 px-3 gradient-primary rounded-lg text-sm font-medium hover:opacity-90 transition-all"
                              >
                                Manage
                              </Link>
                              <button
                                onClick={() => handleReleaseCharacter(char.id, !char.is_public)}
                                className={`py-2 px-3 rounded-lg text-sm transition-all ${
                                  char.is_public
                                    ? "bg-gray-500/20 text-gray-300 hover:bg-gray-500/30"
                                    : "bg-green-500/20 text-green-300 hover:bg-green-500/30"
                                }`}
                              >
                                {char.is_public ? "Unrelease" : "Release"}
                              </button>
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            )}
          </>
        )}
      </main>
    </div>
  );
}
